apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: production-
namespace: production

commonAnnotations:
  note: This environment is production

resources:
  - ../../base
  
patchesStrategicMerge:
  - replicas-patch.yaml

configMapGenerator:
  - name: kustomize-poc-config-map
    envs:
    - ".env"